# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('changelog.json', '.'),
    ],
    hiddenimports=[
        'openpyxl', 'pandas', 'numpy',
        'tkinter', 'tkinter.ttk', 'tkinter.filedialog',
        'tkinter.messagebox', 'tkinter.scrolledtext',
        'domain.alt_material.alt_manager',
        'storage.storage',
        'config.settings',
        'config.paths',
        'utils.helpers',
        'logger',
        'exceptions',
        'analysis.analyzer',
        'analysis.sheets.sheet1_summary',
        'analysis.sheets.sheet2_alt',
        'analysis.sheets.sheet3_no_note',
        'analysis.sheets.sheet4_middle',
        'analysis.sheets.sheet5_full',
        'analysis.sheets.sheet6_anomaly',
        'analysis.sheets.sheet7_amount',
        'analysis.sheets.sheet8_reason_summary',
        'analysis.sheets.sheet9_reason_detail',
        'analysis.sheets.sheet10_trend',
        'analysis.sheets.write_sheet_util',
        'export.ppt.ppt_generator',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ZPP011_偏差分析器_v36',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['ZPP011偏差分析器.ico'],
)
