# gen.py - 生成 tests/test_pyside6_migration.py
import os

Q = '"'   # ASCII double quote
DQ = '"'  # same

def line(s):
    return s

out = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'tests', 'test_pyside6_migration.py'), 'w', encoding='utf-8')
L = []

def a(s):
    L.append(s)

a('# -*- coding: utf-8 -*-')
a('"""PySide6 迁移核心模块测试（无需 GUI 窗口）"""')
a('import sys, os')
a("sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))")
a('')
a('import pytest')
a('import pandas as pd')
a('import tempfile')
a('import json')
a('')
a('from PySide6.QtCore import Qt')
a('from PySide6.QtWidgets import QApplication')
a('from gui_pyside6.models.data_frame_model import DataFrameModel')
a('from core.rule_engine import RuleEngine')
a('from core.import_handlers import import_alt_pairs_from_excel')
a('')
a('')
a('# ---------- Qt Application Fixture ----------')
a('@pytest.fixture(scope=' + Q + 'session' + Q + ', autouse=True)')
a('def qapp():')
a('    app = QApplication.instance()')
a('    if app is None:')
a('        app = QApplication([])')
a('    return app')
a('')
a('')
a('# ---------- TestDataFrameModel ----------')
a('class TestDataFrameModel:')
a('    def test_row_count(self, qapp):')
a('        df = pd.DataFrame({' + Q + 'A' + Q + ': [1, 2], ' + Q + 'B' + Q + ': [' + Q + 'a' + Q + ', ' + Q + 'b' + Q + ']})')
a('        model = DataFrameModel(df)')
a('        assert model.rowCount() == 2')
a('        assert model.columnCount() == 2')
a('')
a('    def test_display_role(self, qapp):')
a('        df = pd.DataFrame({' + Q + 'A' + Q + ': [1, 2]})')
a('        model = DataFrameModel(df)')
a('        assert model.data(model.index(0, 0)) == ' + Q + '1' + Q)
a('        assert model.data(model.index(1, 0)) == ' + Q + '2' + Q)
a('')
a('    def test_edit_enabled_only_remark(self, qapp):')
a('        df = pd.DataFrame({' + Q + '备注' + Q + ': [' + Q + 'x' + Q + '], ' + Q + '其他' + Q + ': [' + Q + 'y' + Q + ']})')
a('        model = DataFrameModel(df)')
a('        idx = model.index(0, df.columns.get_loc(' + Q + '备注' + Q + '))')
a('        assert model.flags(idx) & Qt.ItemIsEditable')
a('        idx2 = model.index(0, df.columns.get_loc(' + Q + '其他' + Q + '))')
a('        assert not (model.flags(idx2) & Qt.ItemIsEditable)')
a('')
a('    def test_set_data_updates_df(self, qapp):')
a('        df = pd.DataFrame({' + Q + '备注' + Q + ': [' + Q + Q + ']})')
a('        model = DataFrameModel(df)')
a('        idx = model.index(0, 0)')
a('        assert model.setData(idx, ' + Q + '新备注' + Q + ', Qt.EditRole) is True')
a('        assert model.getDataFrame().iloc[0][' + Q + '备注' + Q + '] == ' + Q + '新备注' + Q)
a('')
a('')
a('# ---------- TestRuleEngine ----------')
a('class TestRuleEngine:')
a('    def test_should_ai_audit_high_dev_no_remark(self):')
a('        engine = RuleEngine()')
a('        assert engine.should_ai_audit(15.0, ' + Q + Q + ') is True')
a('')
a('    def test_should_ai_audit_low_dev_with_remark(self):')
a('        engine = RuleEngine()')
a('        assert engine.should_ai_audit(5.0, ' + Q + '已备注' + Q + ') is False')
a('')
a('    def test_should_ai_audit_zero_dev(self):')
a('        engine = RuleEngine()')
a('        assert engine.should_ai_audit(0.0, ' + Q + Q + ') is False')
a('')
a('    def test_check_auto_close_condition(self):')
a('        engine = RuleEngine()')
a('        row = {' + Q + '审核状态' + Q + ': ' + Q + '已审核' + Q + ', ' + Q + '备注原因' + Q + ': ' + Q + 'test' + Q + '}')
a('        result = engine.check_auto_close_condition(row)')
a('        assert isinstance(result, bool)')
a('')
a('    def test_get_band_color(self):')
a('        engine = RuleEngine()')
a('        color = engine.get_band_color(15.0)')
a('        assert isinstance(color, str)')
a('        assert color.startswith(' + Q + '#' + Q + ')')
a('')
a('')
a('# ---------- TestImportHandler ----------')
a('class TestImportHandler:')
a('    def test_alt_import_basic(self):')
a('        data = [{' + Q + '工厂名称' + Q + ': ' + Q + '厂A' + Q + ', ' + Q + '物料A编码' + Q + ': ' + Q + 'A1' + Q + ', ' + Q + '物料A名称' + Q + ': ' + Q + 'A1名' + Q + ',')
a('                 ' + Q + '物料B编码' + Q + ': ' + Q + 'B1' + Q + ', ' + Q + '物料B名称' + Q + ': ' + Q + 'B1名' + Q + '}]')
a('        current = []')
a('        result = import_alt_pairs_from_excel(data, current, overwrite=False)')
a('        assert len(result) == 1')
a('        assert result[0][' + Q + 'alt_material_code' + Q + '] == ' + Q + 'B1' + Q)
a('')
a('    def test_alt_import_dedup(self):')
a('        data = [{' + Q + '工厂名称' + Q + ': ' + Q + '厂A' + Q + ', ' + Q + '物料A编码' + Q + ': ' + Q + 'A1' + Q + ', ' + Q + '物料A名称' + Q + ': ' + Q + 'A1名' + Q + ',')
a('                 ' + Q + '物料B编码' + Q + ': ' + Q + 'B1' + Q + ', ' + Q + '物料B名称' + Q + ': ' + Q + 'B1名' + Q + '}]')
a('        current = []')
a('        result = import_alt_pairs_from_excel(data, current, overwrite=False)')
a('        result2 = import_alt_pairs_from_excel(data, result, overwrite=False)')
a('        assert len(result2) >= 1')
a('')
a('')
a("if __name__ == " + Q + "__main__" + Q + ":")
a("    pytest.main([__file__, " + Q + "-v" + Q + "])")
a('')

out.write('\n'.join(L) + '\n')
out.close()
print('Generated test file successfully')
